steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/insightgen-api:latest', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/insightgen-api:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'insightgen-api'
      - '--image=gcr.io/$PROJECT_ID/insightgen-api:latest'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=4Gi'
      - '--cpu=2'
      - '--set-env-vars=STORAGE_MODE=gcs,GCS_BUCKET=${_GCS_BUCKET},OPENAI_OBSERVATIONS_MODEL=${_OPENAI_OBSERVATIONS_MODEL},OPENAI_HEADLINES_MODEL=${_OPENAI_HEADLINES_MODEL},PARALLEL_SLIDES=${_PARALLEL_SLIDES}'
      - '--set-secrets=OPENAI_API=openai-api-key:latest'
      - '--timeout=3600s'
      - '--service-account=cloud-build-service-account@$PROJECT_ID.iam.gserviceaccount.com'

images:
  - 'gcr.io/$PROJECT_ID/insightgen-api:latest'

substitutions:
  _GCS_BUCKET: 'insightgen-generators'  # Default value, override in build trigger
  _OPENAI_OBSERVATIONS_MODEL: 'gpt-4o'  # Default model for observations
  _OPENAI_HEADLINES_MODEL: 'gpt-4o'  # Default model for headlines
  _PARALLEL_SLIDES: '10'

options:
  logging: CLOUD_LOGGING_ONLY
