steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/insightgen-api:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/insightgen-api:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'insightgen-api'
      - '--image=gcr.io/$PROJECT_ID/insightgen-api:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=2Gi'
      - '--cpu=1'
      - '--set-env-vars=STORAGE_MODE=gcs,GCS_BUCKET=${_GCS_BUCKET},OPENAI_API=${_OPENAI_API}'
      - '--timeout=3600s'

images:
  - 'gcr.io/$PROJECT_ID/insightgen-api:$COMMIT_SHA'

substitutions:
  _GCS_BUCKET: 'insightgen-generators'  # Default value, override in build trigger
  _OPENAI_API: ''  # Set this in the build trigger

options:
  logging: CLOUD_LOGGING_ONLY
